name: Docker Image CD

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker login --username yousufkalim --password ${{ secrets.GH_TOKEN }} ghcr.io
        docker build . --tag ghcr.io/yousufkalim/nxt-devops:latest
        docker push ghcr.io/yousufkalim/nxt-devops:latest
